[project]
name        = "turbopipe"
description = "🌀 Fast memoryview data piping"
version     = "2.0.0"
license     = "MIT"
readme      = "readme.md"
requires-python = ">=3.11"
dependencies = []

[project.urls]
GitHub = "https://github.com/BrokenSource/TurboPipe"

[build-system]
requires = ["maturin>=1.9,<2.0"]
build-backend = "maturin"

[tool.maturin]
features    = ["pyo3/extension-module"]
module-name = "turbopipe._turbopipe"

[tool.maturin.generate-ci.github]
trusted-publishing = true
publishing-environment = "release"
