[project]
name        = "turbopipe"
description = "🌀 Fast data piping for python"
version     = "2.1.0"
license     = "MIT"
readme      = "readme.md"
requires-python = ">=3.11"

[project.urls]
GitHub = "https://github.com/BrokenSource/TurboPipe"

[build-system]
requires = ["maturin>=1.9,<2.0"]
build-backend = "maturin"

[tool.maturin]
module-name = "turbopipe._turbopipe"
features = ["turbopipe/python"]

[tool.maturin.generate-ci.github]
publishing-environment = "release"
trusted-publishing = true
